// Vuex Mutations
export const MUTATE_USER = 'MUTATE_USER';
export const MUTATE_TOKEN = 'MUTATE_TOKEN';
export const MUTATE_MEMBERS = 'MUTATE_MEMBERS';
export const MUTATE_HOUSEHOLD = 'MUTATE_HOUSEHOLD';
export const MUTATE_ACTIVITIES = 'MUTATE_ACTIVITIES';
export const MUTATE_CREATEISSUE = 'MUTATE_CREATEISSUE';
export const MUTATE_SOLVEISSUE = 'MUTATE_SOLVEISSUE';
export const MUTATE_REMOVEISSUE = 'MUTATE_REMOVEISSUE';
export const MUTATE_ISSUE = 'MUTATE_ISSUE';
export const MUTATE_FEED = "MUTATE_FEED"
export const MUTATE_IS_ADMIN = "MUTATE_IS_ADMIN"
export const MUTATE_MEMBER_ID = "MUTATE_MEMBER_ID"
// Vuex Actions
export const REQUEST_LOGIN_ACTION = 'REQUEST_LOGIN_ACTION';
export const GET_HOUSEHOLD_ACTIVITIES = 'GET_HOUSEHOLD_ACTIVITIES';
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const GET_TENANT_ACTION = 'GET_TENANT_ACTION';
export const GET_FEED = 'GET_FEED';
export const GET_ISSUES = 'GET_ISSUES';

// Other
export const TOKEN_LOCAL_STORAGE = 'token';
