// Vuex Mutations
export const MUTATE_USER = 'MUTATE_USER';
export const MUTATE_TOKEN = 'MUTATE_TOKEN';
export const MUTATE_MEMBERS = 'MUTATE_MEMBERS';
export const MUTATE_HOUSEHOLD = 'MUTATE_HOUSEHOLD';
export const MUTATE_ACTIVITIES = 'MUTATE_ACTIVITIES';
// Vuex Actions
export const REQUEST_LOGIN_ACTION = 'REQUEST_LOGIN_ACTION';
export const GET_HOUSEHOLD_ACTIVITIES = 'GET_HOUSEHOLD_ACTIVITIES';
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const GET_TENANT_ACTION = 'GET_TENANT_ACTION';
export const GET_FEED = 'GET_FEED';

// Other
export const TOKEN_LOCAL_STORAGE = 'token';
